gText_Birch_Welcome::
	.string "Sorry to keep you waiting!\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "My name is Professor Oak.\p"
	.string "But everyone calls me the\n"
	.string "Pokémon Professor.\p"
	.string "Before we go any further, I'd like\n"
	.string "to tell you a few things you should\l"
	.string "know about this world!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This world is widely inhabited by\n"
	.string "creatures known as Pokémon.\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "We humans live alongside Pokémon\n"
	.string "as friends.\p"
	.string "At times we play together, and at\n"
	.string "other times we work together.\p"
	.string "Some people use their Pokémon to\n"
	.string "battle and develop closer bonds\l"
	.string "with them.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Now, why don't you tell me a little\n"
	.string "bit about yourself?$"

gText_Birch_BoyOrGirl::
	.string "Which kid do you want to\n"
	.string "play as?$"

gText_Birch_WhatsYourName::
	.string "So, you'd like to play as a\n"
	.string "{STR_VAR_1} then?\p"
	.string "Please tell me your name.$"

gText_Birch_SoItsPlayer::
	.string "Your name is {PLAYER}?$"

gText_Birch_YourePlayer::
	.string "{PLAYER}! Are you ready?\p"
	.string "Your very own tale of grand\n"
	.string "adventure is about to unfold.\p"
	.string "Fun experiences, difficult\n"
	.string "experiences, there's so much\l"
	.string "waiting for you!\p"
	.string "Dreams! Adventure!\p"
	.string "Let's go to the world of Pokémon!\p"
	.string "I'll see you later!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "$"

gText_Birch_Farewell::
	.string "{PLAYER}! Are you ready?\p"
	.string "Your very own tale of grand\n"
	.string "adventure is about to unfold.\p"
	.string "Fun experiences, difficult\n"
	.string "experiences, there's so much\l"
	.string "waiting for you!\p"
	.string "Dreams! Adventure!\p"
	.string "Let's go to the world of Pokémon!\p"
	.string "I'll see you later!\p"
	.string "$"
